export { default as Question1 } from "./Question1.tsx"
export { default as Question2 } from "./Question2.tsx"
export { default as Question3 } from "./Question3.tsx"
export { default as Question4 } from "./Question4.tsx"
export { default as Question5 } from "./Question5.tsx"
